# Spring配置
spring:
  datasource:
    # 数据库连接信息
    url: jdbc:mysql://localhost:3306/traveling?serverTimezone=Asia/Shanghai&characterEncoding=utf8
    username: root
    password: root
  # 静态资源配置
  web:
    resources:
      # 静态资源位置
      static-locations: classpath:static,file:d:/file
  # servlet配置
  servlet:
    # 多部分请求配置
    multipart:
      # 最大文件大小
      max-file-size: 100MB
      # 最大请求大小
      max-request-size: 200MB

# 日志配置
logging:
  # 日志级别
  level:
    # 应用级别日志
    com.example.traveling: debug

# MyBatis配置
mybatis:
  # mapper文件位置
  mapper-locations: classpath:mappers/*.xml
  # MyBatis配置选项
  configuration:
    # 将下划线命名规范映射为驼峰式命名规范
    map-underscore-to-camel-case: true

